### ISSUE TITLE
Activate new runners

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTActions#3]
@j-l-s @srcansiz hi guys, best effort request 🙂: can you please activate the three new runners (`ct-ubuntu-24-x` with `x = 2, 3, 4`)?

**Comment by srcansiz** [comment]
Hi @j-l-s,
I am trying to connect to the new runner but I am getting timeout an error. Do you have the same problem?

**Comment by srcansiz** [comment]
@jbcaillau there is a copied runner. It seems that `actions-runner` is up running. Could you please verify if it is visible on `Self-Hosted Runners` in github settings.

**Comment by jbcaillau** [comment]
@srcansiz thanks for the feedback. only seeing the one and only already installed one
![image](https://github.com/user-attachments/assets/9df4260d-9be8-431e-9e92-313b97ed9d34)

**Comment by j-l-s** [comment]
I just declared 3 new ci slaves and renamed the first (for esthetic reasons)
<img width="1179" alt="Screenshot 2024-12-14 at 10 25 52" src="https://github.com/user-attachments/assets/7981bd68-aba1-43e7-b5b2-aa99c0328cf6" />

Next actions will be to correctly defined the runners on these new slaves....

**Comment by j-l-s** [comment]
Done, you can test it to validate the install ? 

<img width="1104" alt="Screenshot 2024-12-16 at 15 29 41" src="https://github.com/user-attachments/assets/a1374ff6-1591-466d-b15f-f8fd9c7efcee" />

**Comment by jbcaillau** [comment]
@PierreMartinon give it a try 🤞🏾
